# Generated by Django 3.0.6 on 2020-05-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'mercado', 'verbose_name_plural': 'mercados'},
        ),
    ]
