# Generated by Django 3.0.6 on 2020-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('markets', '0002_auto_20200529_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='staff',
        ),
        migrations.AddField(
            model_name='market',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_staff', related_query_name='users_staffs', to='staff.Staff'),
        ),
    ]
