# Generated by Django 3.0.6 on 2020-05-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200529_0524'),
        ('markets', '0003_auto_20200529_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='schedule',
        ),
        migrations.AddField(
            model_name='market',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_schedule', related_query_name='users_schedules', to='schedule.Schedule'),
        ),
    ]
