# Generated by Django 3.0.6 on 2020-05-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'horario', 'verbose_name_plural': 'horarios'},
        ),
    ]
